---
# Docker compose formatted system.
# NOTE: NB_PREFIX has to be set to "/" as an environment variable if running locally. 
# If running via tycho from CommonsShare AppStore, tycho will set the variable.
version: "3.0"
services:
  rshiny:
    image: rocker/shiny:3.4.4
    ports:
      - 3838:3838
#    volumes:
#      - pvc://cloud-top:/mydata
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 64000M
        reservations:
          cpus: '1'
          memory: 1000M 
