version: "3.6"
services:
  octave:
    image: helxplatform/cloudtop-octave:develop-0.0.2
    container_name: octave
    env:
     - VNC_RESOLUTION=1980x1024
    entrypoint: /init
    ports:
      - 8080:8080
    volumes:
      - pvc://cloud-top:/data
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 64000M
        reservations:
          cpus: '1'
          memory: 4000M 
